remote-swagger:
  endpoints:
    player:
      create-player-endpoint: "http://3.68.165.45/player/create/%s"
      delete-player-endpoint: "http://3.68.165.45/player/delete/%s"
      get-specified-player-endpoint: "http://3.68.165.45/player/get"
      get-all-players-endpoint: "http://3.68.165.45/player/get/all"
      update-player-endpoint: "http://3.68.165.45/player/update/%s/%s"
  users:
    default-supervisor-user:
      id: 1
      login: supervisor
      #password can be set using any other options, e.g. in local.properties
      screenName: testSupervisor
      gender: male
      age: 28
      role: supervisor

    default-admin-user:
      id: 2
      login: admin
      #password can be set using any other options, e.g. in local.properties
      screenName: testAdmin
      gender: female
      age: 28
      role: admin